package com.haha.maolin;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import mao.test.greendaodemo_my.bean.Detail;
import mao.test.greendaodemo_my.bean.Yao;

import com.haha.maolin.DetailDao;
import com.haha.maolin.YaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig detailDaoConfig;
    private final DaoConfig yaoDaoConfig;

    private final DetailDao detailDao;
    private final YaoDao yaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        detailDaoConfig = daoConfigMap.get(DetailDao.class).clone();
        detailDaoConfig.initIdentityScope(type);

        yaoDaoConfig = daoConfigMap.get(YaoDao.class).clone();
        yaoDaoConfig.initIdentityScope(type);

        detailDao = new DetailDao(detailDaoConfig, this);
        yaoDao = new YaoDao(yaoDaoConfig, this);

        registerDao(Detail.class, detailDao);
        registerDao(Yao.class, yaoDao);
    }
    
    public void clear() {
        detailDaoConfig.clearIdentityScope();
        yaoDaoConfig.clearIdentityScope();
    }

    public DetailDao getDetailDao() {
        return detailDao;
    }

    public YaoDao getYaoDao() {
        return yaoDao;
    }

}
