package com.haha.maolin;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import mao.test.greendaodemo_my.bean.Staff;
import mao.test.greendaodemo_my.bean.User;

import com.haha.maolin.StaffDao;
import com.haha.maolin.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig staffDaoConfig;
    private final DaoConfig userDaoConfig;

    private final StaffDao staffDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        staffDaoConfig = daoConfigMap.get(StaffDao.class).clone();
        staffDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        staffDao = new StaffDao(staffDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Staff.class, staffDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        staffDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public StaffDao getStaffDao() {
        return staffDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
