package com.syswin.maolin;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import toon.syswin.greendaodemo_my.bean.User;
import toon.syswin.greendaodemo_my.bean.Staff;

import com.syswin.maolin.UserDao;
import com.syswin.maolin.StaffDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig staffDaoConfig;

    private final UserDao userDao;
    private final StaffDao staffDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        staffDaoConfig = daoConfigMap.get(StaffDao.class).clone();
        staffDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        staffDao = new StaffDao(staffDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Staff.class, staffDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        staffDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public StaffDao getStaffDao() {
        return staffDao;
    }

}
